apiVersion: v1
kind: ConfigMap
metadata:
  name: storefront-config
  namespace: desigo
data:
  NODE_ENV: "production"
  PORT: "8000"
  MEDUSA_BACKEND_URL: "http://backend-service:9000"
  NEXT_PUBLIC_BASE_URL: "http://storefront-service:8000"
  NEXT_PUBLIC_DEFAULT_REGION: "dk"
